### ISSUE TITLE
Tooltips causing issues with server side rendering

### ISSUE THREAD

**Issue by macjuul** [antoniandre/wave-ui#78] opened 2021-12-25 21:46 UTC
Hello!

I ran into a problem where WTooltip is throwing an error using nuxt SSR due to the use of `window`.

![image](https://user-images.githubusercontent.com/7606171/147394064-e50b9be7-abd5-4b02-86dd-358a2e38c8b5.png)

I can make a bypass for now however it would be great if the tooltip component has a SSR check built in.

Thanks!

**Comment by antoniandre** [comment] 2021-12-30 03:05
Hi @macjuul,
thanks for reporting. This should now be fixed in version 1.45.14.
Could you let me know if the issue is gone on your end? 
If not please reopen the issue and share your code and the full error message including the line number. :)

**Closed by antoniandre** 2021-12-30 03:05 UTC

**Comment by macjuul** [comment] 2021-12-30 15:56
Can confirm it's working as intended now 🙂
